---
  - name: Installation de server web
    hosts: web
    remote_user: root
    vars:
      user: seb
      domain: test
      repo: denis_web
      token_slack: "T9TTWMCNL/BDFJZMYSZ/rljAho2mxxOiV3En6ap8rT55"
      channel_slack: "#ansible"
      domain_slack: "freeforlive.slack.com"

    roles:
      - apache
      - php
      - git

  - name: Installation de mysql
    hosts: bdd
    remote_user: root

    roles:
      - mysql
      - notifSlack
...
